### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by pythonmobile** [sebastianlipponer/zorder_knn#1]
On an ubuntu box.

```
[ 34%] Built target googletest-patch
[ 37%] Performing build step for 'googletest-debug'
CMake Error at /tmp/zorder_knn/.extern/build/googletest-debug-prefix/src/googletest-debug-stamp/googletest-debug-build-.cmake:49 (message):
  Command failed: 2

   '/usr/bin/gmake'

  See also

    /tmp/zorder_knn/.extern/build/googletest-debug-prefix/src/googletest-debug-stamp/googletest-debug-build-*.log


gmake[2]: *** [CMakeFiles/googletest-debug.dir/build.make:86: googletest-debug-prefix/src/googletest-debug-stamp/googletest-debug-build] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/googletest-debug.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
build-extern.sh: 17: popd: not found```

**Comment by sebastianlipponer** [comment]
Thanks for pointing this out. The compilation issue should be gone with most recent master.

**Comment by pythonmobile** [comment]
Thanks! Can you please add this to the documentation: For Ubuntu users, please make sure gtest is installed using "sudo apt-get install libgtest-dev".

**Comment by sebastianlipponer** [comment]
So `build-extern.sh` is successful, but you still run into an error where CMake doesn't find `GTest` and you fixed that by installing it via apt? This shouldn't happen. In fact it doesn't on my Debian system using CMake 3.25.1. I see `GTest_DIR` in `CMakeCache.txt` pointing to the `.extern` folder. Also GitHub's action for Linux running on Ubuntu seems to be fine. Not sure if this environment has a preinstalled GTest.

Which CMake version do you use?

**Comment by pythonmobile** [comment]
On my mac m1:

cmake --version
cmake version 3.29.2

And I still get: 

```-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/ccache/libexec/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at tests/CMakeLists.txt:1 (find_package):
  Could not find a package configuration file provided by "GTest" with any of
  the following names:

    GTestConfig.cmake
    gtest-config.cmake

  Add the installation prefix of "GTest" to CMAKE_PREFIX_PATH or set
  "GTest_DIR" to a directory containing one of the above files.  If "GTest"
  provides a separate development package or SDK, be sure it has been
  installed.```

On my ubuntu box, this error is gone. My cmake is version 3.22.1

**Comment by sebastianlipponer** [comment]
> On my ubuntu box, this error is gone.

Good to know.

I don't have a Mac to test with homebrew under MacOS, but from what you report the behavior of CMake seems to be different. I assume you are able to run `build-extern.sh` successfully, but the subsequent CMake configure step fails to find GTest.

Could you please paste the list of files in `.extern/install` after running `build-extern.sh`, i.e. the output of `find .extern/install`?
